# This is the configuration used to check the rubocop source code.

# inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs
  # - rubocop-performance
  # - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.4

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*

Style/IpAddresses:
  # The test for this cop includes strings that would cause offenses
  Exclude:
  - spec/rubocop/cop/style/ip_addresses_spec.rb

Style/Documentation:
  Exclude:
  - 'app/**/*'
  - 'config/**/*'

Style/ClassAndModuleChildren:
  Exclude:
  - 'app/**/*'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - instance_methods
      - protected_methods
      - private_methods

# Trailing white space is meaningful in code examples
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/AlignHash:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Lint/BooleanSymbol:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'
    - 'db/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/LineLength:
  Exclude:
    - 'lib/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'Rakefile'
    - 'app/mailers/*.rb'
    # - '**/*.rake'
    # - 'spec/**/*.rb'
    # - '**/*.gemspec'

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/config_obsoletion.rb

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

# RSpec/PredicateMatcher:
#   EnforcedStyle: explicit
#
# RSpec/MessageSpies:
#   EnforcedStyle: receive
#
# RSpec/NestedGroups:
#   Max: 7
